default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: nusucheck_development

test:
  <<: *default
  database: nusucheck_test

production:
  <<: *default
  database: nusucheck_production
  username: nusucheck
  password: <%= ENV["NUSUCHECK_DATABASE_PASSWORD"] %>
